name: Simple Github Search Application continuous deployment

on:
    push:
        branches:
            - wip

jobs:
    buildimage:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout Github Action'
          uses: actions/checkout@v4

        - name: 'Login via Azure CLI'
          uses: azure/login@v2
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/simple-github-search:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/simple-github-search:${{ github.sha }}

        - name: 'Deploy to Azure App Sevices'
          uses: 'azure/webapps-deploy@v2'
          with:
            app-name: 'gaappwebapp'
            images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/simple-github-search:${{ github.sha }}'

        - name: 'Azure logout'
          run: |
            az logout
